const SET_FETCHING_STATE = 'student/SET_FETCHING_STATE';
const SET_MODAL_OPEN_STATE = 'student/SET_MODAL_OPEN_STATE';

const ADD_STUDENT_SUCCESS = 'student/ADD_SUCCESS';
const UPDATE_STUDENT_SUCCES = 'student/UPDATE__SUCCES';
const DELETE_SUCCES = 'student/DELETE_SUCCES';

const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
const FETCH_STUDENT_ERROR = 'FETCH_STUDENT_ERROR';

const GET_STUDENT_NATIONALITY = 'GET_STUDENT_NATIONALITY';
const UPDATE_STUDENT_NATIONALITY = 'UPDATE_STUDENT_NATIONALITY';

const TOGGLE_STUDENT_APPROVED = 'TOGGLE_STUDENT_APPROVED';

// Roles
const ROLE_PROFILE = 'ROLE_PROFILE';
const ROLE_REGISTRAR_PROFILE = 'ROLE_REGISTRAR_PROFILE';
const ROLE_ADMIN_PROFILE = 'ROLE_ADMIN_PROFILE';

export default {
    SET_FETCHING_STATE,
    SET_MODAL_OPEN_STATE,

    GET_STUDENT_NATIONALITY,
    UPDATE_STUDENT_NATIONALITY,

    FETCH_STUDENT_SUCCESS,
    FETCH_STUDENT_ERROR,

    ADD_STUDENT_SUCCESS,
    DELETE_SUCCES,
    UPDATE_STUDENT_SUCCES,

    TOGGLE_STUDENT_APPROVED,

    ROLE_PROFILE,
    ROLE_REGISTRAR_PROFILE,
    ROLE_ADMIN_PROFILE,
};
