const SET_FETCHING_STATE = 'student/SET_FETCHING_STATE';
const SET_MODAL_OPEN_STATE = 'student/SET_MODAL_OPEN_STATE';
const SET_MODAL_MODE = 'student/SET_MODAL_MODE';
const LOAD_STUDENT_DATA_TO_MODAL = 'student/LOAD_STUDENT_DATA_TO_MODAL';
const CLEAR_STUDENT_DATA_TO_MODAL = 'student/CLEAR_STUDENT_DATA_TO_MODAL';

const ADD_STUDENT_SUCCESS = 'student/ADD_SUCCESS';
const UPDATE_STUDENT_SUCCES = 'student/UPDATE__SUCCES';
const DELETE_SUCCES = 'student/DELETE_SUCCES';

const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
const FETCH_STUDENT_ERROR = 'FETCH_STUDENT_ERROR';

const FILL_ALL_NATIONALITIES = 'FILL_ALL_NATIONALITIES';
const GET_STUDENT_NATIONALITY = 'GET_STUDENT_NATIONALITY';
const UPDATE_STUDENT_NATIONALITY = 'UPDATE_STUDENT_NATIONALITY';

// Roles
const SET_ROLE = 'SET_ROLE';

export default {
    SET_FETCHING_STATE,
    SET_MODAL_OPEN_STATE,
    SET_MODAL_MODE,
    LOAD_STUDENT_DATA_TO_MODAL,
    CLEAR_STUDENT_DATA_TO_MODAL,

    FILL_ALL_NATIONALITIES,
    GET_STUDENT_NATIONALITY,
    UPDATE_STUDENT_NATIONALITY,

    FETCH_STUDENT_SUCCESS,
    FETCH_STUDENT_ERROR,

    ADD_STUDENT_SUCCESS,
    DELETE_SUCCES,
    UPDATE_STUDENT_SUCCES,

    SET_ROLE,
};
