const SET_FAMILY_MEMBER_SUCCESS = 'SET_FAMILY_MEMBER_SUCCESS';

const ADD_FAMILY_MEMBER_SUCCESS = 'ADD_FAMILY_MEMBER_SUCCESS';
const UPDATE_FAMILY_MEMBER_SUCCES = 'UPDATE_FAMILY_MEMBER_SUCCES';
const DELETE_FAMILY_MEMBERSUCCES = 'DELETE_FAMILY_MEMBERSUCCES';

const FETCH_FAMILY_MEMBER_SUCCESS = 'FETCH_FAMILY_MEMBER_SUCCESS';
const FETCH_FAMILY_MEMBER_ERROR = 'FETCH_FAMILY_MEMBER_ERROR';

const SET_NATIONALITY_SUCCESS = 'SET_NATIONALITY_SUCCESS';
const GET_ALL_NATIONALITY_SUCCESS = 'GET_ALL_NATIONALITY_SUCCESS';

const ADD_NATIONALITY_SUCCESS = 'ADD_NATIONALITY_SUCCESS';
const UPDATE_NATIONALITY_SUCCESS = 'UPDATE_NATIONALITY_SUCCESS';
const DELETE_NATIONALITY_SUCCESS = 'DELETE_NATIONALITY_SUCCESS';

export default {

    SET_FAMILY_MEMBER_SUCCESS,

    ADD_FAMILY_MEMBER_SUCCESS,
    DELETE_FAMILY_MEMBERSUCCES,
    UPDATE_FAMILY_MEMBER_SUCCES,

    FETCH_FAMILY_MEMBER_SUCCESS,
    FETCH_FAMILY_MEMBER_ERROR,

    SET_NATIONALITY_SUCCESS,
    GET_ALL_NATIONALITY_SUCCESS,

    ADD_NATIONALITY_SUCCESS,
    UPDATE_NATIONALITY_SUCCESS,
    DELETE_NATIONALITY_SUCCESS,
};
